Fix: default export all Store types
lukas2005/-types-orbit-db pull request #14
Opened 2019-10-18 19:06 UTC by reasv

In the OrbitDB JS source code all stores are default exports (https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L512), however without this patch the type definitions use named exports.

As a result it's impossible to import them and use them in Typescript; importing `Store` for example wouldn't cause a compile error, but it does break at runtime since  `Store` remains `undefined` after being imported.

This is not an issue when using OrbitDB normally because you don't have to import any of the `Store` subclasses.
However if you want to make your own store by extending `Store`, you're met with a runtime error when writing `class X extends Store {}`, the latter being `undefined`

This pull request fixes that.

I also had to move an interface in its own file, because it was in the Store.d.ts file, which uses default export now and can't have another export in it.

2019-10-19 11:31 UTC, RichardLitt commented
@lukas2005 Sound right to you?

2019-10-20 12:28 UTC, reasv commented
I've noticed that Identity.d.ts has a similar problem, only the default export works because it exports a few things that are default exported in their original modules.
So it needs to be broken up in a few different files, and all that.

2019-10-20 19:30 UTC, tmorin commented
hi @reasv ,

> I've noticed that Identity.d.ts has a similar problem, only the default export works because it exports a few things that are default exported in their original modules.
> So it needs to be broken up in a few different files, and all that.

Yes, you're right about `Identity.d.ts`. In deed only the class `Identities` can be fetched from the index' module `orbit-db-identity-provider`. Others like `IdentityProvider` or `Identity` are not reachable.

In #18 I wrote unit tests for this module. There, I implemented a custom provider which requires the class `IdentityProvider`. This class can only be loaded from `node_modules/orbit-db-identity-provider/src/identity-provider-interface.js `. So ...

```typescript
import Identities, {Identity, IdentityProviderInterface, IdentityProviderOptions} from 'orbit-db-identity-provider';
import UntypedIdentityProviderInterface from 'orbit-db-identity-provider/src/identity-provider-interface';
const IdentityProvider = UntypedIdentityProviderInterface as typeof IdentityProviderInterface;
```

I do not how to declare types in TypeScript which are not reachable directly from the module's index ...

I guess some work have to be done in the `orbit-db`'s modules to fully support TypeScript.

Best regards

2019-10-21 05:44 UTC, reasv commented
If I understand your question correctly we had the same doubt.
I solved this by directly declare-ing the submodule(s) like so 

declare module 'orbit-db-identity-provider/src/identity-provider-interface' 

In a separate file.
And then just importing them the same way

2019-10-21 05:49 UTC, reasv commented
I did it for the AccessController module
https://github.com/nabladelta/bernkastel/tree/master/src/OrbitDBAccessControllers
I will also merge thos with orbit-db-types eventually, for now it's part of my app

2019-10-21 07:08 UTC, tmorin commented
Hi @reasv 

> I did it for the AccessController module
> https://github.com/nabladelta/bernkastel/tree/master/src/OrbitDBAccessControllers
> I will also merge those types with orbit-db-types eventually, for now it's part of my app

Thanks for the message. I've been able to refactor `orbit-db-identity-provider` accordingly.

Best regards

2019-10-21 09:33 UTC, reasv commented
Update: I've moved my typings of the AccessController modules into my fork of orbit-db-types.
I'll make a pull request as soon as I'm sure they're working well
https://github.com/reasv/orbit-db-types/tree/master/OrbitDBAccessControllers

2019-10-21 18:09 UTC, lukas2005 commented
Looks right

2019-10-26 12:41 UTC, m00nwtchr approved these changes

2019-10-26 12:42 UTC, m00nwtchr requested changes
Cant you just use `export default` instead of adding a `export = XXX` line?

2019-10-26 16:30 UTC, reasv commented
I will do that.

2019-10-28 22:11 UTC, reasv commented
Done @lukas2005

2019-10-31 01:27 UTC, reasv commented
@lukas2005 can you accept my pull request now?

2019-10-31 14:26 UTC, m00nwtchr approved these changes

2019-10-31 14:26 UTC, merged